### ISSUE TITLE
Cannot Use

### ISSUE THREAD

**Issue by raevillena** [Martin36/react-gauge-chart#1]
Should I install d3 as dev dependency? or should I install it alongside this module?

**Comment by raevillena** [comment]
using npm install wont install this module, I tried to pull it from this repo. BTW

**Comment by raevillena** [comment]
Fix for me: installed d3 as independent package.

did npm install d3 --save to the application modules

**Comment by Martin36** [comment]
@raevillena It shouldn't be that way, I will add it to the dependencies instead of devDependencies
