### ISSUE TITLE
dependency issue with react 18

### ISSUE THREAD

**Issue by murtazav** [Martin36/react-gauge-chart#101]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nftist-app@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.2 || ^17.0" from react-gauge-chart@0.4.0
npm ERR! node_modules/react-gauge-chart
npm ERR!   react-gauge-chart@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/xyz/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xyz/.npm/_logs/2022-06-25T18_58_01_668Z-debug-0.log

**Comment by benjaminchevoor** [comment]
Same here

**Comment by joao-dantas-yssy** [comment]
> same here, any solution ?

i instaled using "--legacy-peer-deps" flag,
npm install react-gauge-chart --legacy-peer-deps

**Comment by SchmitzAndrew** [comment]
I had the same issue and the above fix didn't work, just ended up downgrading react.

**Comment by ecolip** [comment]
I use npm install react-gauge-chart --legacy-peer-deps, but can't resolve the problem.
