### ISSUE TITLE
Customize Range Value and Text 

### ISSUE THREAD

**Issue by fl0at-on** [Martin36/react-gauge-chart#12]
Gauge reflects a metric from 1-100, but want to have a 'custom' range to show a metric between 50-150%, etc. Can calculate the converted percentage to fit the gauge, but the textLabel shows the conversion

Simpler Request: allow a textValue override to show an custom value/string. If not given, default is the percentage. String to allow both "125%", or "High Risk!" type of information.

More Involved Request: Set a lower/upper range to convert the calculated percentage against (default being 1/100%), so the user doesn't have to calculate the ranges ad hoc.

Thanks!

**Comment by Martin36** [comment]
So, just to see if I understand you right, you want a new prop added such as `range` which is a array that takes the min and max values, then the percentage value would be calculated with that range in mind?

One solution would be to add two new props `label` and the `range` and keep the percentage. The percentage would then represent a value between the min value and the max value in the range. The default range would be 0-100 and default label would be to show the percentage.

**Comment by ferrao** [comment]
Just the `textValue` override would be great and easy to implement, if I submit a PR will you merge it @fl0at-on ?

**Comment by Martin36** [comment]
@ferrao You can do that, but please also add some information in the README file on how to use it

**Comment by ferrao** [comment]
Thanks @Martin36, I will do that, sorry for wrongly addressing my question to the issue reporter ;)

**Comment by ferrao** [comment]
@Martin36, I was going to pick this up, but just this [PR](https://github.com/Martin36/react-gauge-chart/pull/24) that addresses the same issue.

If that PR is moving forward soon, I think it is best not to duplicate work, what do you think?

**Comment by Thebarda** [comment]
@ferrao I'm currently working on it

**Comment by Thebarda** [comment]
Since #24 has been merged, can we close this issue ?
