### ISSUE TITLE
Error: require() of ES Module

### ISSUE THREAD

**Issue by alphawhiskey03** [Martin36/react-gauge-chart#125]
When i import GaugeChart in my next.js app

i'm on version 0.4.1

```
Error: require() of ES Module /Users/vignesh/projects/diet-edu/node_modules/d3/src/index.js from /Users/vignesh/projects/diet-edu/node_modules/react-gauge-chart/dist/GaugeChart/index.js not supported.
Instead change the require of /Users/vignesh/projects/diet-edu/node_modules/d3/src/index.js in /Users/vignesh/projects/diet-edu/node_modules/react-gauge-chart/dist/GaugeChart/index.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by Brady-MacDonald** [comment]
Currently experiencing the same issue.

**Comment by develth** [comment]
same here

**Comment by suvantorw** [comment]
Experiencing the same issue in both version `0.4.1` and `0.4.0`
```
Build error occurred
Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/d3/src/index.js from .../node_modules/react-gauge-chart/dist/GaugeChart/index.js not supported.
Instead change the require of .../node_modules/d3/src/index.js in .../node_modules/react-gauge-chart/dist/GaugeChart/index.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by sshehab1** [comment]
I have the same issue

**Comment by VerioN1** [comment]
same , did someone managed to solve this?

**Comment by rafaelpoa** [comment]
Does anyone have a solution?

**Comment by claw5439** [comment]
I have the same issue.

**Comment by rafaelpoa** [comment]
I found this and it worked. It is using version 0.3.0

Works 100% in nextjs

[https://codesandbox.io/s/y9jlp?file=/package.json](url)

**Comment by tnemelclement** [comment]
Same issue.

**Comment by script8888** [comment]
> When i import GaugeChart in my next.js app
> 
> i'm on version 0.4.1
> 
> ```
> Error: require() of ES Module /Users/vignesh/projects/diet-edu/node_modules/d3/src/index.js from /Users/vignesh/projects/diet-edu/node_modules/react-gauge-chart/dist/GaugeChart/index.js not supported.
> Instead change the require of /Users/vignesh/projects/diet-edu/node_modules/d3/src/index.js in /Users/vignesh/projects/diet-edu/node_modules/react-gauge-chart/dist/GaugeChart/index.js to a dynamic import() which is available in all CommonJS modules.
> ```

Did you get a solution? Pls share or if you found another resource to achieve the gauge chart

**Comment by tnemelclement** [comment]
Something worked for me, but it's only a temporary solution : 

In `node_module/react-chart-gauge/package.json` add `"type" : "module"`

In the file `GaugeChart/index.js` replace `var _d = require("d3")` by `import * as _d from 'd3'`

Then in the files :
- `index.js`
- `GaugeChart/index.js`
- `GaugeChart/customHooks.js`

replace all the other `require("?????")` by `import ??? from "????"`

Then in your component or page you want to use the chart, add : 
```
import dynamic from "next/dynamic";

const GaugeChart = dynamic(() => import('react-gauge-chart'), { ssr: false });
```

**Comment by alphawhiskey03** [comment]
> > When i import GaugeChart in my next.js app
> > i'm on version 0.4.1
> > ```
> > Error: require() of ES Module /Users/vignesh/projects/diet-edu/node_modules/d3/src/index.js from /Users/vignesh/projects/diet-edu/node_modules/react-gauge-chart/dist/GaugeChart/index.js not supported.
> > Instead change the require of /Users/vignesh/projects/diet-edu/node_modules/d3/src/index.js in /Users/vignesh/projects/diet-edu/node_modules/react-gauge-chart/dist/GaugeChart/index.js to a dynamic import() which is available in all CommonJS modules.
> > ```
> 
> Did you get a solution? Pls share or if you found another resource to achieve the gauge chart

i haven't found the solution exactly yet but when i downgraded the version to  "react-gauge-chart@0.3.0" the gauge chart worked for me

**Comment by script8888** [comment]
> import dynamic from "next/dynamic";
> const GaugeChart = dynamic(() => import('react-gauge-chart'), { ssr: false });

Dope
this solves it
