### ISSUE TITLE
Change SVG neadle 

### ISSUE THREAD

**Issue by Mansoun** [Martin36/react-gauge-chart#146]
Hello . 
I want to make some changes to Neadle SVG. 
If you put a prop for getting svg file for neadle is good.

otherwise, can you help me or guide me on how to do that? 

thanks.

**Comment by kashaudhan** [comment]
Add a pr #153 to achieve the same.

**Comment by jenathrash** [comment]
Hi.  I still don't see anything new in the https://www.npmjs.com/package/react-gauge-chart?activeTab=readme.  It still shows last published 1 year ago.  How do we take advantage of this new code to use custom needles?
