### ISSUE TITLE
d3 dependency

### ISSUE THREAD

**Issue by DominicTobias** [Martin36/react-gauge-chart#16]
Hey thanks the component looks good. I am concerned about unecessary bloat though since you import * from d3: https://github.com/Martin36/react-gauge-chart/blob/master/src/lib/GaugeChart/index.js

Instead you should import the things you need i.e. `import { arc, pie } from 'd3'`

Also I see you're using create-react-app which isn't suitable for component libraries. Imo d3 should be listed in `externals` of the webpack config for example and listed as a `peerDependency` in package.json.

Or else you could compile a CJS and ESM version with packa.json `module` entry pinting at the ESM version and most users could import the ESM version so that d3 is properly tree-shaken without that measure ^^

**Comment by Martin36** [comment]
@DominicTobias Thanks for the information. 

I have changed the imports so that only the relevant parts of D3 is included. 

I'm a bit unfamiliar with creating npm packages. Do you have any good guide/tutorial on how to create a module without create-react-app?

Thanks

**Comment by smchinna** [comment]
Check my repo:
  I created NPM without create react app
   https://github.com/smchinna/adapt-data-table/tree/Update

 If you want I will do and I will create PR.

**Comment by Martin36** [comment]
Yes that is true
