### ISSUE TITLE
Default props support removec warning shown in the console

### ISSUE THREAD

**Issue by gauravsoni119** [Martin36/react-gauge-chart#165]
It looks like the warning message is already addressed in #151 pull request. But the latest version(0.4.1) doesn't have these changes. It looks like the new [tag](https://github.com/Martin36/react-gauge-chart/blob/v0.5.0/src/lib/GaugeChart/index.js) is also generated.
Can you release the new version in the npm registry?

![Screenshot from 2024-04-15 22-02-33](https://github.com/Martin36/react-gauge-chart/assets/8476712/559376dd-1158-4d40-80ab-045f16d87080)

**Comment by Martin36** [comment]
The latest version 0.5.1 is released on NPM now.

**Comment by gauravsoni119** [comment]
> The latest version 0.5.1 is released on NPM now.

Thanks for the quick release and reply.!!
