### ISSUE TITLE
Render Stacks Up

### ISSUE THREAD

**Issue by raevillena** [Martin36/react-gauge-chart#2]
whenever there is a change in the states, it draws new gauge below the previous one instead of redrawing the original.

**Comment by raevillena** [comment]
downloaded the whole repository and now fixed the issue I encountered. 

Also: This is a react module, it is obvious that there might somebody who will use redux or any state machine that use setState method to rerender this component which I have issues with. ->> Ive modified the this component to fix: (1) the stacking rendered svg and (2) the pointer that always start moving from 0 Value. 

Ill update this thread for the modification. Ill keep it open for now. Thanks Martin for this great Component

**Comment by Martin36** [comment]
@raevillena Thanks for letting me know, I will look into the issue

**Comment by raevillena** [comment]
This stacking issue was probably because of other module <resizeme> which makes the component aware of its container size and rerender this component to the new size and with the same ID stacks them up. propbably closing this issue now
