### ISSUE TITLE
Styling issue when use multiple same guage-charts with the same Id

### ISSUE THREAD

**Issue by haideralishah** [Martin36/react-gauge-chart#20]
Why you use `Id` attribute in react.

**Comment by Martin36** [comment]
To be able to render multiple charts. Is there a better way?

**Comment by sanzhardanybayev** [comment]
Using ID for determining the type is the worst idea. I cannot render multiple charts of the same type as well.

**Comment by sanzhardanybayev** [comment]
I looked source code, it uses that to instantiate **D3 chart**

**Comment by sanzhardanybayev** [comment]
> Why you use `Id` attribute in react.

Just use different **ids** for each element. I append **Date.now()** to each ID to make it unique.
