### ISSUE TITLE
Package can't be used

### ISSUE THREAD

**Issue by wnyao** [Martin36/react-gauge-chart#3]
After installed using yarn, error **module not found** were shown. This happen both on local environment and a codesandbox environment. Tried troubleshoot by installing d3 (as refer to related issue), still not successful.

This is the [codesandbox example](https://codesandbox.io/s/m931xo3y) that i used. The error can be seen shortly after when the page loaded.

**Comment by patricktownley** [comment]
Same!

**Comment by Martin36** [comment]
Thanks for the notice. I will look into it

**Comment by Martin36** [comment]
@wnyao I updated the package and it should work now. I changed some code in your sandbox example https://codesandbox.io/embed/13yx9nv4jq . It works for me, can you check that it also works for you?

**Comment by wnyao** [comment]
@Martin36 Thanks for resolving it, it is working for me. Just curious whether is it because of the babel transpiling issue? saw the new commit on your fix for transpiling the component. I am learning about building component library as well, will be great to hear about the issue.

**Comment by Martin36** [comment]
@wnyao Yes, I think that was the problem. I also added D3 to the package dependencies, but the transpiling issue was definatly a problem

**Comment by wnyao** [comment]
@Martin36 Noted. Amazing work on the gauge chart btw.

**Comment by Martin36** [comment]
@wnyao Thank you
