### ISSUE TITLE
Gauge is hidden when the DIV is 'display:block'

### ISSUE THREAD

**Issue by rlocatelli9** [Martin36/react-gauge-chart#49]
When a DIV's display property is dynamic ('block' or 'none') Gauge is hidden when the DIV is display: block;
When the DIV is display: block, I need the gauge-chart component inside it not to be hidden.

**Comment by asathkumara** [comment]
> When a DIV's display property is dynamic ('block' or 'none') Gauge is hidden when the DIV is display: block; When the DIV is display: block, I need the gauge-chart component inside it not to be hidden.

Did you manage to resolve this issue?
