### ISSUE TITLE
Im using id="gauge-chart3" but the gauge doesn't change style

### ISSUE THREAD

**Issue by gabrieloureiro** [Martin36/react-gauge-chart#55]
![image](https://user-images.githubusercontent.com/39869298/93650516-19914800-f9e5-11ea-9781-74ded0edcad1.png)

![image](https://user-images.githubusercontent.com/39869298/93650538-2746cd80-f9e5-11ea-9a80-70de48fd8810.png)

**Comment by Martin36** [comment]
What are you trying to achieve? It seems like the color is what you specified in the code
