### ISSUE TITLE
formatting text/label

### ISSUE THREAD

**Issue by sstant** [Martin36/react-gauge-chart#6]
is it possible to format the text/label by rendering a string? specifically I'm looking to remove the % percentage symbol from the label. thanks!

**Comment by Martin36** [comment]
@sstant So you mean that instead of the prop `percent={0.86}` you would add the percentage yourself, like this: `percent="86%"`. Or would it be better to have another prop specifying if the percentage should be shown, like this: `showPercentage=true`?

**Comment by sstant** [comment]
using a string like percent="86" would achieve the goal of omitting the percentage sign, or something like formatText={str => str.replace('%', '')}
