### ISSUE TITLE
Feature Request : Custom arcs width and height

### ISSUE THREAD

**Issue by Thebarda** [Martin36/react-gauge-chart#7]
It could be interesting to add prop that allow to custom arcs widht and / or height.
I guess the prop could like this `Array[{width: number, height: number}]`

**Comment by Martin36** [comment]
@Thebarda Just to clarify, do you mean that each individual part of the arc should be customizable? Like the green, yellow and red of the default chart?

**Comment by Thebarda** [comment]
Yes, exactly ! 
If user does not provide something about arcs style, it should use default (current) behavior

**Comment by Martin36** [comment]
I see, I think this could be nice to have, at least for the width of the arcs. 
The structure of the array could be a set of ints, which represents the percentage that arc should fill. All the numbers would then need to add up to 100 (or 1 if decimals are used). 

But I am not so sure about why it would be needed to set the individual height for the arcs

**Comment by Thebarda** [comment]
Yes, I totally agree with your structure. 
Yep, arc's height is not very important

**Comment by Thebarda** [comment]
Should "nbOfLevels" prop exists anymore ?

**Comment by Martin36** [comment]
Sorry for the late reply, but I just checked out your pull request and it looks great! 
Just wondering how the `arcsLength` prop will work with the `nrOfLevels`. 

Should the `nrOfLevels` prop be removed or should we have the `arcsLength` prop "take over" the arc lengths?

**Comment by Martin36** [comment]
I saw that you wrote a comment in the code for that, great. We will do it that way

**Comment by Martin36** [comment]
Merged your pull request so I'm closing this issue now

**Comment by Thebarda** [comment]
Thank you for your merge :)
