### ISSUE TITLE
0.4 release on npm

### ISSUE THREAD

**Issue by The-Funk** [Martin36/react-gauge-chart#78]
Hi Martin,

I love this library but I can't find release 0.4 on npm. Do you have plans to push the new release to npm?

**Comment by Martin36** [comment]
You can find version 0.4 here: https://github.com/Martin36/react-gauge-chart/packages/898608

**Comment by Martin36** [comment]
Now it should be published to npm also

**Comment by peterturquoise** [comment]
Hi Martin, I also love the library, it's simple to use and the gauges look really good.
I have a small problem it currently, I'm using tabs and when on one tab I show some gauges which  render beautifully initially, but when I go to a different tab and then back to the gauge tab none of the gauges are visible as the entire gauge seems to have had its size set to zero. 

Can you help ?

![image](https://user-images.githubusercontent.com/12343560/129652775-78a18301-576f-495a-ab60-65affca241a4.png)
  
  BR
  
  Peter

**Comment by Martin36** [comment]
> Hi Martin, I also love the library, it's simple to use and the gauges look really good.
> I have a small problem it currently, I'm using tabs and when on one tab I show some gauges which render beautifully initially, but when I go to a different tab and then back to the gauge tab none of the gauges are visible as the entire gauge seems to have had its size set to zero.
> 
> Can you help ?
> 
> ![image](https://user-images.githubusercontent.com/12343560/129652775-78a18301-576f-495a-ab60-65affca241a4.png)
> 
> BR
> 
> Peter

Please create a separate issue for this
